import {createHash,createHmac,randomBytes,randomUUID,scrypt as scryptCallback,timingSafeEqual} from 'node:crypto';
import {promisify} from 'node:util';
import {contentOf,pollView,imageTypes,uploadLimit,uuidPattern} from './post-content.js';
const scrypt=promisify(scryptCallback);
export const PUBLIC_ORIGIN='https://www.lowpolyworks.com';
export const AUTHOR_ORIGIN='https://lowpolyworks-internal-tracker.vercel.app';
export const fail=(status,message)=>{throw Object.assign(Error(message),{status});};
export const digest=value=>createHash('sha256').update(value).digest('hex');
const usernameOf=value=>{const username=text(value,40,'a username').toLowerCase();if(!/^[a-z0-9][a-z0-9._-]{1,39}$/.test(username))fail(400,'Use 2-40 letters, numbers, dots, underscores or hyphens for the username.');return username;};
const token=()=>randomBytes(32).toString('base64url');
const safeEqual=(a,b)=>{const x=Buffer.from(String(a)),y=Buffer.from(String(b));return x.length===y.length&&timingSafeEqual(x,y);};
const emailOf=value=>{if(typeof value!=='string'||value.length>254||!/^\S+@[^\s@]+\.[^\s@]+$/.test(value))fail(400,'Enter a valid email address.');return value.trim().toLowerCase();};
const text=(value,max,label,optional=false)=>{if(typeof value!=='string'||value.trim().length>max||!optional&&!value.trim())fail(400,'Enter '+label+'.');return value.trim();};
const urlOf=(value,optional=true)=>{if(!value&&optional)return '';let url;try{url=new URL(value);}catch{fail(400,'Enter a full https:// link.');}if(url.protocol!=='https:'||url.username||url.password||url.href.length>2000)fail(400,'Enter a full https:// link.');return url.href;};
export function iconOf(value){if(!value)return '';if(typeof value!=='string'||value.length>180000||!/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/]+={0,2}$/.test(value))fail(400,'Choose a PNG, JPG or WebP icon smaller than 130 KB.');return value;}
export function initialState(){return {version:1,authors:[],posts:[],subscribers:[],invites:[],notifications:[],limits:{},uploads:[],projects:[{id:'mdlxl',name:'MDLxL',description:'A Warcraft III model editor.',url:'https://github.com/UnsctMagic/MDLxL'},{id:'warhammercraft',name:'WarhammerCraft',description:'Warhammer armies and models for Warcraft III.',url:'#armies'}]};}
export async function hashPassword(password){if(typeof password!=='string'||password.length<12||password.length>256)fail(400,'Use a password between 12 and 256 characters.');const salt=token();return salt+':'+(await scrypt(password,salt,64)).toString('hex');}
export async function checkPassword(password,stored){if(typeof password!=='string'||password.length>256||!stored)return false;const [salt,hash]=stored.split(':');return safeEqual((await scrypt(password,salt,64)).toString('hex'),hash);}
export function validatePost(input,state){const kind=input.kind;if(!['news','model-upload','model-update'].includes(kind))fail(400,'Choose news, a new model, or a model update.');const projectId=input.projectId||null;if(projectId&&!state.projects.some(p=>p.id===projectId))fail(400,'Choose an existing project.');const link=urlOf(input.link);if(kind!=='news'&&!link)fail(400,'Model posts need a link to the upload or update.');return {title:text(input.title,160,'a title'),body:text(input.body||'',20000,'post text',Boolean(input.poll||input.media?.length||input.videos?.length)),kind,projectId,link};}
const authorView=a=>({id:a.id,name:a.name,icon:a.icon||'',role:a.role,nameGraphic:a.username==='unsanctionedmagic'?'https://www.lowpolyworks.com/ui/unsanctionedmagic-name.png':null});
export function publicFeed(state,voterKey){return {projects:state.projects,posts:state.posts.slice().sort((a,b)=>b.publishedAt.localeCompare(a.publishedAt)).map(post=>({...post,poll:pollView(post.poll,voterKey?.(post.id)),author:authorView(state.authors.find(a=>a.id===post.authorId)||{id:post.authorId,name:'Author'})}))};}
export function createPublishing({store,env=process.env,sendEmail,mailConfigured,now=()=>Date.now(),createUploadToken,inspectUpload}){
 const secret=()=>{if(!env.PUBLISHING_SESSION_SECRET||env.PUBLISHING_SESSION_SECRET.length<32)fail(503,'Author login is not configured yet.');return env.PUBLISHING_SESSION_SECRET;};
 const sign=value=>createHmac('sha256',secret()).update(value).digest('base64url');
 const cookie=(value,maxAge=28800)=>`lpw_session=${value}; Path=/api/publishing; HttpOnly; Secure; SameSite=Strict; Max-Age=${maxAge}`;
 function session(value){if(typeof value!=='string')return null;const [payload,signature]=value.split('.');if(!payload||!signature||!safeEqual(signature,sign(payload)))return null;try{const data=JSON.parse(Buffer.from(payload,'base64url').toString());return data.exp>now()?data:null;}catch{return null;}}
 const csrf=value=>sign('csrf:'+value);
 function authenticate(state,request,write=false){const data=session(request.session);const author=data&&state.authors.find(a=>a.id===data.id&&a.sessionVersion===data.version);if(!author)fail(401,'Please log in.');if(write&&!safeEqual(request.csrf||'',csrf(request.session)))fail(403,'Your session changed. Reload the author page.');return author;}
 async function limit(request,action,max){const key=action+':'+digest((request.ip||'unknown')+secret()),time=now();const allowed=await store.mutate(state=>{for(const [id,value] of Object.entries(state.limits))if(value.until<time)delete state.limits[id];const value=state.limits[key]||{count:0,until:time+15*60*1000};if(value.count>=max)return false;value.count++;state.limits[key]=value;return true;});if(!allowed)fail(429,'Too many attempts. Please try again in 15 minutes.');}
 const unsubscribeToken=email=>sign('unsubscribe:'+email);
 const unsubscribeUrl=email=>AUTHOR_ORIGIN+'/author.html#unsubscribe='+encodeURIComponent(Buffer.from(email).toString('base64url')+'.'+unsubscribeToken(email));
 const setSession=author=>{const payload=Buffer.from(JSON.stringify({id:author.id,version:author.sessionVersion,exp:now()+28800000,nonce:token()})).toString('base64url');return cookie(payload+'.'+sign(payload));};
 async function deliver(request){
  if(!mailConfigured(env))fail(503,'Model notification delivery is not connected yet.');
  const {state}=await store.read();authenticate(state,request,true);const lease=token(),time=now();
  const work=await store.mutate(s=>{authenticate(s,request,true);const job=s.notifications.find(j=>j.recipients.some(id=>!j.sent.includes(id))&&(!j.lease||j.lease.until<time));if(!job)return null;if(job.firstAttemptAt&&time-job.firstAttemptAt>23*3600000&&job.uncertain)fail(409,'An earlier email result needs review before retrying.');job.lease={token:lease,until:time+60000};job.firstAttemptAt??=time;job.uncertain=true;return {id:job.id,post:job.post,recipients:job.recipients.filter(id=>!job.sent.includes(id)).slice(0,5).map(id=>s.subscribers.find(sub=>sub.id===id)).filter(Boolean)};});
  if(!work){const {state:latest}=await store.read();return {remaining:latest.notifications.reduce((n,j)=>n+j.recipients.filter(id=>!j.sent.includes(id)).length,0),sent:0};}
  const results=await Promise.all(work.recipients.map(async sub=>{if(!sub.confirmed)return {id:sub.id,skipped:true};try{await sendEmail({to:sub.email,subject:work.post.kind==='model-upload'?'New model: '+work.post.title:'Model update: '+work.post.title,text:work.post.title+'\n\n'+work.post.body+'\n\n'+work.post.link+'\n\nYou subscribed to new model uploads and model updates only. News posts never trigger these emails.\nUnsubscribe: '+unsubscribeUrl(sub.email),headers:{'List-Unsubscribe':`<${unsubscribeUrl(sub.email)}>`}},'lpw-model/'+work.id+'/'+sub.id,env);return {id:sub.id};}catch(error){return {id:sub.id,error:error.message};}}));
  return store.mutate(s=>{const job=s.notifications.find(j=>j.id===work.id);if(!job||job.lease?.token!==lease)fail(409,'Email delivery is already being handled.');job.sent.push(...results.filter(r=>!r.error).map(r=>r.id));delete job.lease;job.uncertain=results.some(r=>r.error);return {sent:results.filter(r=>!r.error&&!r.skipped).length,remaining:s.notifications.reduce((n,j)=>n+j.recipients.filter(id=>!j.sent.includes(id)).length,0),error:results.find(r=>r.error)?.error};});
 }
 async function execute(action,input={},request={}){
  if(action==='feed'){if(input.visitorId&&!uuidPattern.test(input.visitorId))fail(400,'Invalid voter ID.');const {state}=await store.read();return {...publicFeed(state,input.visitorId?id=>digest(id+':'+input.visitorId.toLowerCase()+secret()):undefined),modelNotificationsEnabled:mailConfigured(env)};}
  if(action==='vote'){if(!uuidPattern.test(input.visitorId||'')||!uuidPattern.test(input.postId||'')||!Number.isInteger(input.option))fail(400,'Choose a poll option with a valid voter ID.');return store.mutate(s=>{const post=s.posts.find(p=>p.id===input.postId);if(!post?.poll)fail(404,'Poll not found.');if(input.option<0||input.option>=post.poll.options.length)fail(400,'Choose an available option.');const key=digest(post.id+':'+input.visitorId.toLowerCase()+secret());post.poll.votes??={};if(Object.hasOwn(post.poll.votes,key))fail(409,'You have already voted in this poll.');post.poll.votes[key]=input.option;return {poll:pollView(post.poll,key)};});}
  if(action==='delivery')return deliver(request);
  if(action==='login'){
   await limit(request,'login',12);const username=usernameOf(input.username),{state}=await store.read(),author=state.authors.find(a=>a.username===username);
   const valid=await checkPassword(input.password,author?.password||'unknown-account:'+ '0'.repeat(128));if(!author||!valid)fail(401,'Username or password is incorrect.');return {author:authorView(author),cookie:setSession(author)};
  }
  if(action==='activate'){
   await limit(request,'activate',12);const username=usernameOf(input.username),password=await hashPassword(input.password),name=text(input.name,60,'your display name'),credential=digest(String(input.token||''));
   const author=await store.mutate(state=>{if(state.authors.some(a=>a.username===username))fail(409,'That account already exists. Log in instead.');let role='author';if(!state.authors.some(a=>a.role==='owner')&&username===env.PUBLISHING_OWNER_USERNAME?.trim().toLowerCase()&&env.PUBLISHING_SETUP_TOKEN_HASH&&safeEqual(credential,env.PUBLISHING_SETUP_TOKEN_HASH))role='owner';else{const invite=state.invites.find(i=>i.username===username&&safeEqual(i.tokenHash,credential)&&i.expiresAt>now()&&!i.used);if(!invite)fail(403,'This invitation is invalid or has expired.');invite.used=true;}const row={id:randomUUID(),username,name,icon:'',password,role,sessionVersion:1};state.authors.push(row);return row;});return {author:authorView(author),cookie:setSession(author)};
  }
  if(action==='subscribe'){
   if(!mailConfigured(env))fail(503,'Model notifications are not enabled yet. Please check back later.');await limit(request,'subscribe',5);const email=emailOf(input.email),id=digest(email),confirmation=token();
   await store.mutate(state=>{let sub=state.subscribers.find(s=>s.id===id);if(sub?.confirmed)return;if(!sub){sub={id,email,confirmed:false,createdAt:new Date(now()).toISOString()};state.subscribers.push(sub);}sub.confirmationHash=digest(confirmation);sub.confirmationExpires=now()+86400000;});
   const {state}=await store.read();if(!state.subscribers.find(s=>s.id===id)?.confirmed)await sendEmail({to:email,subject:'Confirm model notifications — LowPolyWorks',text:'Only new model uploads and model updates. No news, no general announcements. This is not a spamletter.\n\nConfirm your signup:\n'+AUTHOR_ORIGIN+'/author.html#confirm='+id+'.'+confirmation+'\n\nIf you did not request this, ignore this email.'},'lpw-confirm/'+confirmation,env);
   return {message:'Check your email to confirm. You will receive model uploads and model updates only.'};
  }
  if(action==='confirm'){const [id,credential]=String(input.token||'').split('.');await store.mutate(state=>{const sub=state.subscribers.find(s=>s.id===id&&safeEqual(s.confirmationHash||'',digest(credential||''))&&s.confirmationExpires>now());if(!sub)fail(400,'This confirmation has expired. Please sign up again.');sub.confirmed=true;delete sub.confirmationHash;delete sub.confirmationExpires;});return {message:'Confirmed. You will receive new model uploads and model updates only. No news.'};}
  if(action==='unsubscribe'){const [encoded,signature]=String(input.token||'').split('.');const email=Buffer.from(encoded||'','base64url').toString();if(!signature||!safeEqual(signature,unsubscribeToken(email)))fail(400,'This unsubscribe link is invalid.');await store.mutate(s=>{const sub=s.subscribers.find(row=>row.id===digest(email));if(sub){sub.confirmed=false;delete sub.confirmationHash;delete sub.confirmationExpires;}});return {message:'Unsubscribed. You will receive no more model notifications.'};}
  const {state}=await store.read(),author=authenticate(state,request,action!=='me');
  if(action==='me')return {author:authorView(author),csrf:csrf(request.session),projects:state.projects,posts:publicFeed(state).posts.filter(p=>author.role==='owner'||p.authorId===author.id),mailEnabled:mailConfigured(env),subscribers:author.role==='owner'?state.subscribers.filter(s=>s.confirmed).length:undefined,pendingNotifications:state.notifications.reduce((n,j)=>n+j.recipients.filter(id=>!j.sent.includes(id)).length,0)};
  if(action==='upload-token'){
   if(!imageTypes.includes(input.type))fail(400,'Upload a PNG, JPG, WebP or GIF.');if(!Number.isInteger(input.size)||input.size<1||input.size>uploadLimit)fail(400,'Each image or GIF must be at most 20 MB.');
   const name=text(input.name,180,'a file name'),id=randomUUID(),extension={'image/png':'png','image/jpeg':'jpg','image/webp':'webp','image/gif':'gif'}[input.type],pathname='publishing/media/'+author.id+'/'+id+'.'+extension;
   const clientToken=await createUploadToken({pathname,type:input.type,size:input.size});
   await store.mutate(s=>{const current=authenticate(s,request,true);s.uploads??=[];s.uploads.push({id,authorId:current.id,pathname,name,type:input.type,size:input.size,ready:false});});return {id,pathname,clientToken};
  }
  if(action==='upload-complete'){
   const upload=(state.uploads||[]).find(u=>u.id===input.id&&u.authorId===author.id);if(!upload)fail(404,'Upload not found.');const blob=await inspectUpload(upload.pathname);if(blob.contentType!==upload.type||blob.size!==upload.size)fail(400,'The upload does not match the selected image.');
   return store.mutate(s=>{authenticate(s,request,true);const row=s.uploads.find(u=>u.id===upload.id);row.ready=true;return {media:{id:row.id,name:row.name,type:row.type,url:AUTHOR_ORIGIN+'/api/media?id='+row.id}};});
  }
  if(action==='logout'){await store.mutate(s=>{authenticate(s,request,true).sessionVersion++;});return {cookie:cookie('',0)};}
  if(action==='profile'){const name=text(input.name,60,'your display name'),icon=iconOf(input.icon);return store.mutate(s=>{const current=authenticate(s,request,true);current.name=name;current.icon=icon;return {author:authorView(current)};});}
  if(action==='publish')return store.mutate(s=>{const current=authenticate(s,request,true),content={...validatePost(input,s),...contentOf(input,s,current.id)};if(typeof input.id!=='string'||!/^[a-f0-9-]{36}$/.test(input.id))fail(400,'A post ID is required.');const existing=s.posts.find(p=>p.id===input.id);if(existing){if(existing.authorId!==current.id)fail(403,'This post belongs to another author.');return {post:{...existing,poll:pollView(existing.poll)}};}const post={id:input.id,authorId:current.id,...content,publishedAt:new Date(now()).toISOString()};s.posts.push(post);if(post.kind!=='news')s.notifications.push({id:post.id,post:{...post},recipients:s.subscribers.filter(sub=>sub.confirmed).map(sub=>sub.id),sent:[]});return {post:{...post,poll:pollView(post.poll)}};});
  if(author.role!=='owner')fail(403,'Only the owner can manage authors and projects.');
  if(action==='invite'){const username=usernameOf(input.username),invitation=token();await store.mutate(s=>{const owner=authenticate(s,request,true);if(owner.role!=='owner')fail(403,'Owner access required.');if(s.authors.some(a=>a.username===username))fail(409,'That author already has an account.');s.invites=s.invites.filter(i=>i.username!==username&&i.expiresAt>now()&&!i.used);s.invites.push({username,tokenHash:digest(invitation),expiresAt:now()+7*86400000,used:false});});return {url:AUTHOR_ORIGIN+'/author.html#invite='+invitation+'&username='+encodeURIComponent(username),expires:'7 days'};}
  if(action==='project'){const id=text(input.id,60,'a project ID');if(!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(id))fail(400,'Use lowercase letters, numbers and hyphens for the project ID.');const project={id,name:text(input.name,60,'a project name'),description:text(input.description,300,'a short description'),url:urlOf(input.url,false)};return store.mutate(s=>{const owner=authenticate(s,request,true);if(owner.role!=='owner')fail(403,'Owner access required.');if(s.projects.some(p=>p.id===id))fail(409,'That project ID already exists.');s.projects.push(project);return {project};});}
  fail(404,'Unknown action.');
 }
 return {execute};
}
