import {authorIdentity,postMedia,postPoll} from './post-content.js?v=20261007-media-polls';
import {browserVisitorId} from './visitor-id.js';
const API='https://lowpolyworks-internal-tracker.vercel.app/api/publishing';
const escape=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const labels={news:'News','model-upload':'New model','model-update':'Model update'};
const paragraphs=text=>String(text).split(/\n\s*\n/).map(p=>`<p>${escape(p).replace(/\n/g,'<br>')}</p>`).join('');
function postCard(post,projects){const project=projects.find(p=>p.id===post.projectId),date=new Date(post.publishedAt);return `<article class="post" id="post-${escape(post.id)}"><div class="post-meta">${authorIdentity(post.author)}<a href="#post/${escape(post.id)}"><time datetime="${escape(post.publishedAt)}">${escape(date.toLocaleDateString(undefined,{year:'numeric',month:'short',day:'numeric'}))}</time></a></div><h2><a href="#post/${escape(post.id)}">${escape(post.title)}</a></h2><div class="post-body">${paragraphs(post.body)}</div>${post.link?`<a class="post-link" href="${escape(post.link)}" target="_blank" rel="noopener noreferrer">${post.kind==='news'?'Read more':'View model'} ↗</a>`:''}${postMedia(post.media,post.videos)}${postPoll(post.id,post.poll)}<div class="post-tags"><span>${labels[post.kind]}</span>${project?`<a href="#project/${escape(project.id)}">${escape(project.name)}</a>`:''}</div></article>`;}
export async function renderJournal(app,isCurrent){
 app.onclick=null;let visitorId;try{visitorId=browserVisitorId();}catch{}
 const hash=location.hash,projects=await fetch('projects.json').then(r=>r.json());if(!isCurrent())return;
 document.title='LowPolyWorks';
 if(hash==='#subscribe'){app.innerHTML=`<section class="signup"><a class="quiet-link" href="#feed">← Posts</a><h1>Model notifications</h1><p>Not a spamletter. Just a notification when new models are uploaded or existing models are updated.</p><p class="muted">No news posts. No general project announcements. Unsubscribe at any time.</p><form id="subscribe-form"><label for="subscriber-email">Your email</label><div class="signup-row"><input id="subscriber-email" name="email" type="email" autocomplete="email" maxlength="254" required placeholder="you@example.com"><button type="submit">Notify me</button></div><p id="signup-result" role="status"></p></form></section>`;
 const signupButton=document.querySelector('#subscribe-form button');signupButton.disabled=true;
 try{const response=await fetch(API+'?action=feed',{cache:'no-store'});if(!response.ok)throw Error('Notification signup is temporarily unavailable.');const status=await response.json();if(!isCurrent())return;signupButton.disabled=!status.modelNotificationsEnabled;if(!status.modelNotificationsEnabled)document.querySelector('#signup-result').textContent='Email delivery is not connected yet. Signup will open once it is ready.';}catch(error){if(!isCurrent())return;document.querySelector('#signup-result').textContent=error.message;}
 document.querySelector('#subscribe-form').onsubmit=async event=>{event.preventDefault();const button=event.target.querySelector('button'),status=document.querySelector('#signup-result');button.disabled=true;status.textContent='Saving…';try{const response=await fetch(API+'?action=subscribe',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:new FormData(event.target).get('email')})});const result=await response.json();if(!response.ok)throw Error(result.error||'Please try again.');status.textContent=result.message;event.target.reset();}catch(error){status.textContent=error.message;}finally{button.disabled=false;}};return;}
 app.innerHTML='<p class="journal-loading">Loading posts…</p>';
 let data,error;try{const response=await fetch(API+'?action=feed'+(visitorId?'&visitorId='+encodeURIComponent(visitorId):''),{cache:'no-store'});if(!response.ok)throw Error('Posts are temporarily unavailable.');data=await response.json();}catch(e){error=e;data={posts:[],projects};}if(!isCurrent())return;
 const allProjects=data.projects;
 const projectId=hash.startsWith('#project/')?hash.slice(9):null,postId=hash.startsWith('#post/')?hash.slice(6):null;
 const project=projectId&&allProjects.find(p=>p.id===projectId);
 if(projectId&&!project){app.innerHTML='<h1>Project not found</h1><a href="#feed">Posts</a>';return;}
 const posts=data.posts.filter(p=>(!projectId||p.projectId===projectId)&&(!postId||p.id===postId));
 if(project)document.title=project.name+' — LowPolyWorks';
 if(postId&&posts[0])document.title=posts[0].title+' — LowPolyWorks';
 app.innerHTML=`${project?`<section class="project-heading"><a class="quiet-link" href="#feed">← Posts</a><h1>${escape(project.name)}</h1><p>${escape(project.description)}</p><a class="post-link" href="${escape(project.url)}" ${project.url.startsWith('#')?'':'target="_blank" rel="noopener noreferrer"'}>${project.id==='warhammercraft'?'Explore armies & models':'Open project'} ↗</a></section>`:postId?'<a class="quiet-link" href="#feed">← Posts</a>':'<h1>Posts</h1>'}<div class="post-feed">${error?`<p class="feed-empty" role="status">${escape(error.message)} <button id="reload-posts" class="text-button">Try again</button></p>`:posts.length?posts.map(p=>postCard(p,allProjects)).join(''):`<p class="feed-empty">${postId?'Post not found.':'No posts yet.'}</p>`}</div>`;
 app.onclick=async event=>{const button=event.target.closest('.poll-option');if(!button||button.disabled)return;const section=button.closest('[data-poll]'),status=section.querySelector('.poll-status');try{if(!visitorId)throw Error('Allow browser storage to vote once with a saved ID.');section.querySelectorAll('button').forEach(b=>b.disabled=true);const response=await fetch(API+'?action=vote',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({postId:section.dataset.poll,visitorId,option:Number(button.dataset.option)})});const result=await response.json();if(!isCurrent())return;if(!response.ok)throw Error(result.error||'Your vote could not be saved.');section.outerHTML=postPoll(section.dataset.poll,result.poll);}catch(error){if(!isCurrent())return;status.textContent=error.message;if(!/already voted/.test(error.message))section.querySelectorAll('button').forEach(b=>b.disabled=false);}};
 if(error)document.querySelector('#reload-posts').onclick=()=>renderJournal(app,isCurrent);
}
