import test from 'node:test';
import assert from 'node:assert/strict';
import {createHmac} from 'node:crypto';
import {createPublishing,initialState} from './lib/publishing.js';
import {createHandler} from './api/publishing.js';
import {mailConfigured,sendEmail} from './lib/publishing-mail.js';

function fixture(){
 let state=initialState(),time=Date.now(),writes=Promise.resolve();const mail=[];
 const env={PUBLISHING_SESSION_SECRET:'isolated-follow-test-secret-'.repeat(2),RESEND_API_KEY:'test-key',MODEL_MAIL_FROM:'LowPolyWorks <updates@lowpolyworks.com>'};
 const models=[{id:'graveguard',slug:'grave-guard',name:'Grave Guard'},{id:'vampire',name:'Vampire'}];
 const store={read:async()=>({state:structuredClone(state)}),mutate:fn=>{const task=writes.then(async()=>{const next=structuredClone(state),result=await fn(next);state=next;return result;});writes=task.catch(()=>{});return task;}};
 const service=createPublishing({store,env,mailConfigured,now:()=>time,loadModels:async()=>models,sendEmail:async(message,key)=>{mail.push({message,key});return key;}});
 return {...service,mail,env,get state(){return state;},set time(value){time=value;}};
}
const confirmation=f=>new URLSearchParams(new URL(f.mail.at(-1).message.text.match(/https:\/\/\S+/)[0]).hash.slice(1)).get('follow-confirm');
async function confirmed(f,email='reader@example.test',modelId='graveguard'){await f.execute('follow',{email,modelId},{ip:email});return f.execute('follow-confirm',{token:confirmation(f)});}

test('the sender connects confirmation mail without enabling the global mailer',async()=>{const f=fixture(),feed=await f.execute('feed');assert.equal(feed.modelFollowsEnabled,true);assert.equal(feed.modelNotificationsEnabled,false);await assert.rejects(f.execute('delivery'),{status:503});await assert.rejects(f.execute('subscribe',{email:'reader@example.test'}),{status:400});delete f.env.RESEND_API_KEY;assert.equal((await f.execute('feed')).modelFollowsEnabled,false);await assert.rejects(f.execute('follow',{email:'reader@example.test',modelId:'graveguard'}),{status:503});});
test('a follow needs confirmation, uses the model slug, activates once, and shows the address only with a valid management token',async()=>{const f=fixture();await f.execute('follow',{email:'Reader@example.test',modelId:'graveguard'},{ip:'signup'});assert.deepEqual(f.state.subscribers[0].modelIds,[]);assert.equal(f.state.subscribers[0].confirmed,false);assert(f.mail[0].message.text.includes('/model/grave-guard/#follow-confirm='));const token=confirmation(f);const result=await f.execute('follow-confirm',{token});assert.deepEqual(result.modelIds,['graveguard']);assert.equal(f.state.subscribers[0].email,'reader@example.test');assert.equal(result.email,'reader@example.test');assert(!JSON.stringify(await f.execute('feed')).includes('reader@example.test'));await assert.rejects(f.execute('follow-status',{token:'forged'}),{status:403});assert.deepEqual(await f.execute('follow-status',{token:result.token}),{email:'reader@example.test',modelIds:['graveguard']});await assert.rejects(f.execute('follow-confirm',{token}),{status:400});assert.equal(f.state.notifications.length,0);});
test('verified follows persist, parallel changes preserve both models, and the last uncheck stops emails',async()=>{const f=fixture(),reader=await confirmed(f);await Promise.all([f.execute('follow',{token:reader.token,modelId:'vampire'}),f.execute('follow',{token:reader.token,modelId:'graveguard'})]);assert.deepEqual((await f.execute('follow-status',{token:reader.token})).modelIds.sort(),['graveguard','vampire']);await f.execute('unfollow',{token:reader.token,modelId:'graveguard'});assert.equal(f.state.subscribers[0].confirmed,true);await f.execute('unfollow',{token:reader.token,modelId:'vampire'});assert.equal(f.state.subscribers[0].confirmed,false);assert.deepEqual((await f.execute('follow',{token:reader.token,modelId:'graveguard'})).modelIds,['graveguard']);assert.equal(f.mail.length,1);});
test('an email address alone cannot alter another reader follows; confirmations for two models coexist',async()=>{const f=fixture(),reader=await confirmed(f);await f.execute('follow',{email:'reader@example.test',modelId:'vampire'},{ip:'another-browser'});assert.deepEqual(f.state.subscribers[0].modelIds,['graveguard']);await assert.rejects(f.execute('unfollow',{email:'reader@example.test',modelId:'graveguard'}),{status:403});await assert.rejects(f.execute('follow',{token:reader.token+'bad',modelId:'vampire'}),{status:403});const vampireToken=confirmation(f);await f.execute('follow',{email:'reader@example.test',modelId:'graveguard'},{ip:'another-browser'});await f.execute('follow-confirm',{token:vampireToken});await f.execute('follow-confirm',{token:confirmation(f)});assert.deepEqual(f.state.subscribers[0].modelIds.sort(),['graveguard','vampire']);});
test('unknown models, forged confirmations and expired links never activate',async()=>{const f=fixture();await assert.rejects(f.execute('follow',{email:'reader@example.test',modelId:'unknown'}),{status:404});assert.equal(f.mail.length,0);await f.execute('follow',{email:'reader@example.test',modelId:'graveguard'},{ip:'signup'});const token=confirmation(f);await assert.rejects(f.execute('follow-confirm',{token:token+'bad'}),{status:400});f.time=Date.now()+86400001;await assert.rejects(f.execute('follow-confirm',{token}),{status:400});assert.deepEqual(f.state.subscribers[0].modelIds,[]);assert.equal(f.state.subscribers[0].confirmed,false);});
test('global unsubscribe clears follows, pending links, and saved management credentials',async()=>{const f=fixture(),reader=await confirmed(f),email='reader@example.test';await f.execute('follow',{email,modelId:'vampire'},{ip:'other-device'});const pending=confirmation(f),signature=createHmac('sha256',f.env.PUBLISHING_SESSION_SECRET).update('unsubscribe:'+email).digest('base64url');await f.execute('unsubscribe',{token:Buffer.from(email).toString('base64url')+'.'+signature});assert.deepEqual(f.state.subscribers[0].modelIds,[]);await assert.rejects(f.execute('follow-status',{token:reader.token}),{status:403});await assert.rejects(f.execute('follow-confirm',{token:pending}),{status:400});assert(!JSON.stringify(await f.execute('feed')).includes(email));});
test('public follow actions accept only the existing site origins and JSON POSTs',async()=>{const f=fixture(),handler=createHandler(f);async function call(origin,body={email:'reader@example.test',modelId:'graveguard'},action='follow',method='POST'){const res={headers:{},setHeader(k,v){this.headers[k]=v;},status(code){this.code=code;return this;},json(value){this.body=value;},end(){}};await handler({url:'/api/publishing?action='+action,method,headers:{origin,'content-type':'application/json'},body},res);return res;}assert.equal((await call('https://www.lowpolyworks.com')).code,200);assert.equal((await call('https://attacker.test')).code,403);assert.equal((await call('https://www.lowpolyworks.com',{},'follow-status','GET')).code,405);const reader=await f.execute('follow-confirm',{token:confirmation(f)});assert.deepEqual((await call('https://www.lowpolyworks.com',{token:reader.token},'follow-status')).body,{email:'reader@example.test',modelIds:['graveguard']});});
test('Resend sends as the configured branded address without exposing the API key to the payload',async()=>{const original=globalThis.fetch;let captured;globalThis.fetch=async(url,options)=>{captured={url,options};return {ok:true,json:async()=>({id:'mail-id'})};};try{const f=fixture();assert.equal(await sendEmail({to:'reader@example.test',subject:'Confirm',text:'Confirm'},'unique-follow',f.env),'mail-id');assert.equal(captured.options.headers.Authorization,'Bearer test-key');assert.equal(JSON.parse(captured.options.body).from,'LowPolyWorks <updates@lowpolyworks.com>');assert(!captured.options.body.includes('test-key'));}finally{globalThis.fetch=original;}});
test('changing a model recipient requires confirmation and leaves other follows on the original address',async()=>{
 const f=fixture(),reader=await confirmed(f);
 await f.execute('follow',{token:reader.token,modelId:'vampire'});
 await f.execute('follow',{email:'replacement@example.test',modelId:'graveguard',previousToken:reader.token},{ip:'change-address'});
 assert.equal(f.mail.at(-1).message.to,'replacement@example.test');
 assert.deepEqual((await f.execute('follow-status',{token:reader.token})).modelIds,['graveguard','vampire']);
 const replacement=await f.execute('follow-confirm',{token:confirmation(f)});
 assert.equal(replacement.email,'replacement@example.test');
 assert.deepEqual(replacement.modelIds,['graveguard']);
 assert.deepEqual((await f.execute('follow-status',{token:reader.token})).modelIds,['vampire']);
 assert(!JSON.stringify(await f.execute('feed')).includes('replacement@example.test'));
 await assert.rejects(f.execute('follow',{email:'third@example.test',modelId:'vampire',previousToken:reader.token+'forged'},{ip:'forged-switch'}),{status:403});
});
