export {postBody,contentUrl} from './post-format.js';
const escape=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
export function authorIdentity(author){return `<span class="author-icon">${author.icon?`<img src="${escape(author.icon)}" alt="" width="48" height="48">`:escape(author.name.slice(0,1))}</span><span class="post-author">${author.nameGraphic?`<img class="author-name-graphic" src="${escape(author.nameGraphic)}" alt="${escape(author.name)}" width="156" height="26">`:escape(author.name)}</span>`;}
export function postMedia(media=[],videos=[]){return `${media.length?`<div class="post-media">${media.map(item=>`<a href="${escape(item.url)}" target="_blank" rel="noopener noreferrer"><img src="${escape(item.url)}" alt="${escape(item.name)}" loading="lazy"></a>`).join('')}</div>`:''}${videos.map(video=>video.type==='embed'?`<div class="post-video"><iframe src="${escape(video.embedUrl)}" title="Video" loading="lazy" allow="fullscreen; picture-in-picture; encrypted-media" allowfullscreen referrerpolicy="strict-origin-when-cross-origin"></iframe><a href="${escape(video.url)}" target="_blank" rel="noopener noreferrer">Open video ↗</a></div>`:video.type==='video'?`<video class="post-video-file" controls preload="metadata" src="${escape(video.url)}"></video>`:`<p><a class="post-link" href="${escape(video.url)}" target="_blank" rel="noopener noreferrer">Watch video ↗</a></p>`).join('')}`;}
export function postPoll(postId,poll){
 if(!poll)return '';const voted=Number.isInteger(poll.votedOption);
 return `<section class="post-poll" data-poll="${escape(postId)}"><h3>${escape(poll.question)}</h3>${poll.options.map((option,index)=>{const percentage=poll.total?Math.round(option.votes/poll.total*100):0;return `<button type="button" class="poll-option" data-option="${index}" ${voted?'disabled':''} ${poll.votedOption===index?'aria-pressed="true"':''}><span>${escape(option.label)}${poll.votedOption===index?' ✓':''}</span><small>${option.votes} · ${percentage}%</small><progress max="100" value="${percentage}" aria-label="${escape(option.label)}: ${percentage}%"></progress></button>`;}).join('')}<p class="poll-status" role="status">${poll.total} ${poll.total===1?'vote':'votes'}${voted?' · You voted':' · One vote per browser ID'}</p></section>`;
}
export function videoFromUrl(value){
 const url=new URL(value);if(url.protocol!=='https:'||url.username||url.password)throw Error('Enter a full HTTPS video link.');
 const host=url.hostname.replace(/^www\./,'');let id;if(host==='youtu.be')id=url.pathname.slice(1);else if(['youtube.com','m.youtube.com','youtube-nocookie.com'].includes(host))id=url.searchParams.get('v')||url.pathname.match(/^\/(?:embed|shorts|live)\/([^/]+)/)?.[1];
 if(id&&/^[\w-]{11}$/.test(id))return {url:url.href,type:'embed',embedUrl:'https://www.youtube-nocookie.com/embed/'+id};
 const vimeo=host==='vimeo.com'&&url.pathname.match(/^\/(\d+)(?:\/([a-f0-9]+))?\/?$/)||host==='player.vimeo.com'&&url.pathname.match(/^\/video\/(\d+)\/?$/);
 if(vimeo)return {url:url.href,type:'embed',embedUrl:'https://player.vimeo.com/video/'+vimeo[1]+(vimeo[2]?'?h='+vimeo[2]:'')};
 return {url:url.href,type:/\.(mp4|webm|ogv|ogg)$/i.test(url.pathname)?'video':'link'};
}
