import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {BlobPreconditionFailedError} from '@vercel/blob';
import {createPublishing,initialState,digest,publicFeed,AUTHOR_ORIGIN,PUBLIC_ORIGIN} from './lib/publishing.js';
import {createBlobState} from './lib/publishing-state.js';
import {createHandler} from './api/publishing.js';

function fixture(){let state=initialState(),time=1791360000000,mailEnabled=true;const emails=[];const env={PUBLISHING_SESSION_SECRET:'test-only-secret-'.repeat(3),PUBLISHING_OWNER_USERNAME:'avner',PUBLISHING_SETUP_TOKEN_HASH:digest('test-setup-token')};let writes=Promise.resolve();const store={read:async()=>({state:structuredClone(state)}),mutate:change=>{const task=writes.then(async()=>{const copy=structuredClone(state),result=await change(copy);state=copy;return structuredClone(result);});writes=task.catch(()=>{});return task;}};const service=createPublishing({store,env,now:()=>time,mailConfigured:()=>mailEnabled,sendEmail:async(message,key)=>{emails.push({message,key});return key;}});return {...service,store,emails,get state(){return state;},set time(value){time=value;},set mailEnabled(value){mailEnabled=value;}};}
const password='a-long-test-password';
async function owner(f){const result=await f.execute('activate',{username:'avner',name:'Avner',password,token:'test-setup-token'},{ip:'owner'});const session=result.cookie.match(/^lpw_session=([^;]+)/)[1];const me=await f.execute('me',{}, {session});return {session,csrf:me.csrf,ip:'owner'};}
async function contributor(f,request,username='other'){const invitation=await f.execute('invite',{username},request);const token=new URLSearchParams(new URL(invitation.url).hash.slice(1)).get('invite');const created=await f.execute('activate',{username,name:'Another author',password,token},{ip:username});const session=created.cookie.match(/^lpw_session=([^;]+)/)[1],me=await f.execute('me',{}, {session});return {session,csrf:me.csrf,ip:username};}
const news=()=>({id:randomUUID(),title:'Project news',body:'An announcement.',kind:'news',projectId:'mdlxl',link:''});
const model=()=>({...news(),title:'Updated model',kind:'model-update',projectId:'warhammercraft',link:'https://www.lowpolyworks.com/#model/graveguard'});
async function subscriber(f,email='reader@example.test'){await f.execute('subscribe',{email},{ip:email});const url=f.emails.at(-1).message.text.match(/https:\/\/[^\s]+/)[0],token=new URLSearchParams(new URL(url).hash.slice(1)).get('confirm');await f.execute('confirm',{token});return f.state.subscribers.find(s=>s.email===email);}

test('owner setup is closed without the exact username and one-time setup token',async()=>{const f=fixture();await assert.rejects(f.execute('activate',{username:'attacker',name:'No',password,token:'test-setup-token'},{ip:'other'}),{status:403});await assert.rejects(f.execute('activate',{username:'avner',name:'No',password,token:'wrong'},{ip:'other'}),{status:403});const request=await owner(f);assert.equal((await f.execute('me',{},request)).author.role,'owner');await assert.rejects(f.execute('activate',{username:'avner',name:'No',password,token:'test-setup-token'},{ip:'other'}),{status:409});assert(!JSON.stringify(f.state).includes(password));});
test('password authentication, CSRF, expiry and logout revoke posting access',async()=>{const f=fixture(),request=await owner(f);await assert.rejects(f.execute('publish',news(),{}),{status:401});await assert.rejects(f.execute('publish',news(),{session:request.session}),{status:403});await assert.rejects(f.execute('login',{username:'avner',password:'wrong'},{ip:'login'}),{status:401});const login=await f.execute('login',{username:'avner',password},{ip:'login'});assert(login.cookie.includes('HttpOnly; Secure; SameSite=Strict'));await f.execute('logout',{},request);await assert.rejects(f.execute('me',{},request),{status:401});});
test('sessions expire after eight hours and tampered signatures cannot authenticate',async()=>{const f=fixture(),request=await owner(f);await assert.rejects(f.execute('me',{}, {session:request.session+'changed'}),{status:401});f.time=1791360000000+28800001;await assert.rejects(f.execute('me',{},request),{status:401});});
test('only invited contributors can activate, and they cannot invite authors or add projects',async()=>{const f=fixture(),request=await owner(f),author=await contributor(f,request);await assert.rejects(f.execute('invite',{username:'third'},author),{status:403});await assert.rejects(f.execute('project',{id:'third',name:'Third',description:'Project',url:'https://example.test'},author),{status:403});await f.execute('publish',news(),author);assert.equal(f.state.posts.length,1);const invite=await f.execute('invite',{username:'expired'},request);f.time=1791360000000+8*86400000;await assert.rejects(f.execute('activate',{username:'expired',name:'Expired',password,token:new URLSearchParams(new URL(invite.url).hash.slice(1)).get('invite')},{ip:'expired'}),{status:403});});
test('feed keeps authors, project attachments and order while excluding private account/subscriber data',async()=>{const f=fixture(),request=await owner(f),first=news();await f.execute('publish',first,request);f.time=1791360001000;const author=await contributor(f,request);await f.execute('publish',model(),author);const icon='data:image/png;base64,aGVsbG8=';await f.execute('profile',{name:'Updated name',icon},request);const feed=await f.execute('feed');assert.equal(feed.posts[0].kind,'model-update');assert.equal(feed.posts[1].author.name,'Updated name');assert.equal(feed.posts[1].author.icon,icon);assert.equal(feed.posts[1].projectId,'mdlxl');for(const key of ['password','email','tokenHash','confirmationHash','sessionVersion'])assert(!JSON.stringify(feed).includes('"'+key+'"'));assert.equal(feed.projects.length,2);});
test('model posts require a real https link and reject unknown projects and executable URLs',async()=>{const f=fixture(),request=await owner(f);for(const input of [{...model(),link:''},{...news(),projectId:'unknown'},{...news(),link:'javascript:alert(1)'},{...news(),link:'https://name:password@example.test'}])await assert.rejects(f.execute('publish',input,request),{status:400});assert.equal(f.state.posts.length,0);});
test('retries publish exactly one post and one notification job',async()=>{const f=fixture(),request=await owner(f),post=model();await f.execute('publish',post,request);await f.execute('publish',post,request);assert.equal(f.state.posts.length,1);assert.equal(f.state.notifications.length,1);});
test('news never queues model emails; subscribers must confirm first',async()=>{const f=fixture(),request=await owner(f);await f.execute('subscribe',{email:'unconfirmed@example.test'},{ip:'pending'});await subscriber(f);f.emails.length=0;await f.execute('publish',news(),request);assert.equal(f.state.notifications.length,0);await f.execute('publish',model(),request);assert.equal(f.state.notifications[0].recipients.length,1);await f.execute('delivery',{},request);assert.equal(f.emails.length,1);assert(f.emails[0].message.subject.startsWith('Model update:'));await f.execute('delivery',{},request);assert.equal(f.emails.length,1);});
test('new model uploads notify confirmed readers with the model link',async()=>{const f=fixture(),request=await owner(f);await subscriber(f);f.emails.length=0;const upload={...model(),kind:'model-upload'};await f.execute('publish',upload,request);await f.execute('delivery',{},request);assert.equal(f.emails.length,1);assert(f.emails[0].message.subject.startsWith('New model:'));assert(f.emails[0].message.text.includes(upload.link));});
test('parallel delivery requests share a lease and send each recipient once',async()=>{const f=fixture(),request=await owner(f);await subscriber(f);f.emails.length=0;await f.execute('publish',model(),request);await Promise.all([f.execute('delivery',{},request),f.execute('delivery',{},request)]);assert.equal(f.emails.length,1);assert.equal(f.state.notifications[0].sent.length,1);});
test('unsubscribe prevents queued and future emails; later subscribers do not receive old posts',async()=>{const f=fixture(),request=await owner(f);await subscriber(f);f.emails.length=0;await f.execute('publish',model(),request);await f.execute('delivery',{},request);const url=f.emails[0].message.text.match(/Unsubscribe: (https:\/\/[^\s]+)/)[1],token=new URLSearchParams(new URL(url).hash.slice(1)).get('unsubscribe');await f.execute('unsubscribe',{token});await f.execute('publish',model(),request);assert.equal(f.state.notifications[1].recipients.length,0);await subscriber(f,'later@example.test');f.emails.length=0;await f.execute('delivery',{},request);assert.equal(f.emails.length,0);});
test('missing email configuration never pretends signup or delivery succeeded',async()=>{const f=fixture(),request=await owner(f);f.mailEnabled=false;await assert.rejects(f.execute('subscribe',{email:'reader@example.test'},{ip:'signup'}),{status:503});assert.equal(f.state.subscribers.length,0);await f.execute('publish',model(),request);assert.equal((await f.execute('me',{},request)).mailEnabled,false);await assert.rejects(f.execute('delivery',{},request),{status:503});});
test('persistent login throttling applies across requests',async()=>{const f=fixture();for(let i=0;i<12;i++)await assert.rejects(f.execute('login',{username:'unknown',password:'bad'},{ip:'same'}),{status:401});await assert.rejects(f.execute('login',{username:'unknown',password:'bad'},{ip:'same'}),{status:429});});
test('Blob conditional writes preserve concurrent changes and do not overwrite initial state',async()=>{let content=null,revision=0,conflicts=0;const store=createBlobState({getBlob:async()=>{const snapshot=content,etag=String(revision);return snapshot?{stream:new Blob([snapshot]).stream(),blob:{etag}}:null;},putBlob:async(path,value,options)=>{assert.equal(options.access,'private');if(content===null){assert.equal(options.allowOverwrite,false);content=value;revision++;return;}if(options.ifMatch!==String(revision)){conflicts++;throw new BlobPreconditionFailedError();}content=value;revision++;}});await Promise.all([store.mutate(s=>s.posts.push({id:'a'})),store.mutate(s=>s.posts.push({id:'b'}))]);assert.equal((await store.read()).state.posts.length,2);assert(conflicts>0);});
test('HTTP boundary enforces origins, methods, JSON limits, and cookie/CSRF protection',async()=>{const f=fixture(),request=await owner(f),handler=createHandler(f);async function call(action,{method='POST',origin=AUTHOR_ORIGIN,body={},headers={}}={}){const res={statusCode:0,headers:{},setHeader(k,v){this.headers[k]=v;},status(code){this.statusCode=code;return this;},json(value){this.body=value;},end(){}};await handler({url:'/api/publishing?action='+action,method,headers:{origin,'content-type':'application/json',...headers},body},res);return res;}
 assert.equal((await call('publish',{origin:'https://attacker.test',body:news()})).statusCode,403);
 assert.equal((await call('publish',{origin:PUBLIC_ORIGIN,body:news()})).statusCode,403);
 assert.equal((await call('publish',{method:'GET'})).statusCode,405);
 assert.equal((await call('publish',{body:news()})).statusCode,401);
 assert.equal((await call('publish',{body:news(),headers:{cookie:'lpw_session='+request.session}})).statusCode,403);
 assert.equal((await call('publish',{body:news(),headers:{cookie:'lpw_session='+request.session,'x-csrf-token':request.csrf}})).statusCode,200);
 assert.equal((await call('publish',{headers:{'content-length':'240001'}})).statusCode,413);
 const feed=await call('feed',{method:'GET',origin:PUBLIC_ORIGIN});assert.equal(feed.statusCode,200);assert.equal(feed.headers['Access-Control-Allow-Origin'],PUBLIC_ORIGIN);
});
