import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {renderJournal} from '../dist/journal.js';
const projects=JSON.parse(await fs.readFile(new URL('../dist/projects.json',import.meta.url)));
const post={id:'post-id',author:{name:'<script>bad()</script>',icon:''},title:'<img src=x onerror=bad()>',body:'First paragraph\n\nSecond <b>paragraph</b>',kind:'news',projectId:'mdlxl',publishedAt:'2026-10-07T12:00:00Z',link:''};
async function render(hash,data={projects,posts:[post],modelNotificationsEnabled:false}){const original={fetch:globalThis.fetch,location:globalThis.location,document:globalThis.document};const nodes=new Map(),app={innerHTML:''};globalThis.location={hash};globalThis.document={querySelector:selector=>{if(!nodes.has(selector))nodes.set(selector,{textContent:'',disabled:false});return nodes.get(selector);},title:''};globalThis.fetch=async url=>({ok:true,json:async()=>String(url)==='projects.json'?projects:data});try{await renderJournal(app,()=>true);return {html:app.innerHTML,title:globalThis.document.title,nodes};}finally{Object.assign(globalThis,original);}}
test('the root is a post feed with escaped author/post content and project links',async()=>{const result=await render('');assert.equal(result.title,'LowPolyWorks');assert(result.html.includes('<h1>Posts</h1>'));assert(result.html.includes('&lt;img src=x onerror=bad()&gt;'));assert(result.html.includes('&lt;script&gt;bad()&lt;/script&gt;'));assert(!result.html.includes('<script>'));assert(result.html.includes('#project/mdlxl'));assert(!result.html.includes('army-grid'));});
test('WarhammerCraft is a project leading to the existing catalogue',async()=>{const index=await fs.readFile(new URL('../dist/index.html',import.meta.url),'utf8');assert(/<a[^>]+href="#project\/warhammercraft"/.test(index));assert(/<a[^>]+href="#project\/mdlxl"/.test(index));assert(!index.includes('href="#projects"'));const project=await render('#project/warhammercraft');assert(project.html.includes('href="#armies"'));assert(!project.html.includes('#projects'));assert(project.html.includes('href="#feed"'));assert(project.html.includes('Explore armies &amp; models')||project.html.includes('Explore armies & models'));assert(!project.html.includes(post.title));});
test('model-only subscription copy and pending delivery are visible before signup',async()=>{const result=await render('#subscribe');assert(result.html.includes('Not a spamletter.'));assert(result.html.includes('No news posts.'));assert.equal(result.nodes.get('#subscribe-form button').disabled,true);assert(result.nodes.get('#signup-result').textContent.includes('Email delivery is not connected yet.'));});
test('a stale feed response cannot overwrite a newer route',async()=>{const original={fetch:globalThis.fetch,location:globalThis.location};const app={innerHTML:'New route'};globalThis.location={hash:''};globalThis.fetch=async()=>({json:async()=>projects});try{await renderJournal(app,()=>false);assert.equal(app.innerHTML,'New route');}finally{Object.assign(globalThis,original);}});

test('post identity graphic, original GIF, video and compact poll are rendered',async()=>{const rich={...post,id:'12345678-1234-4234-8234-123456789abc',author:{name:'UnsanctionedMagic',icon:'data:image/png;base64,aGVsbG8=',nameGraphic:'ui/unsanctionedmagic-name.png'},media:[{name:'Animated GIF',url:'https://example.test/image.gif'}],videos:[{type:'embed',url:'https://youtu.be/dQw4w9WgXcQ',embedUrl:'https://www.youtube-nocookie.com/embed/dQw4w9WgXcQ'}],poll:{question:'Which & why?',options:[{label:'A <b>',votes:1},{label:'B',votes:0}],total:1,votedOption:0}};const result=await render('',{projects,posts:[rich]});assert(result.html.includes('author-name-graphic'));assert(result.html.includes('width="48" height="48"'));assert(result.html.includes('image.gif'));assert(result.html.includes('youtube-nocookie.com/embed/'));assert(result.html.includes('Which &amp; why?'));assert(result.html.includes('A &lt;b&gt;'));assert(result.html.includes('disabled'));assert(result.html.includes('You voted'));});
